device: cpu
checkpoint: "logs/test/version_0/checkpoints/last.ckpt"
model:
  class: models.BasicLstmChatter
  parameters:
    max_length: 60
    num_embeddings: 10000
    layers: 2
    hidden_size: 256
    embedding_dim: 128
tokenizer:
  class: tokenizers.SimpleTokenizer
  parameters:
    path: "data/vocab.json"
