device: cpu
checkpoint: "checkpoints/2023-04-21/last.ckpt"
model:
  class: models.BasicLstmChatter
  parameters:
    max_length: 60
    num_embeddings: 10000
    layers: 2
    hidden_size: 256
    embedding_dim: 128
    temperature: 0.5
tokenizer:
  class: tokenizers.SimpleTokenizer
  parameters:
    path: "checkpoints/2023-04-21/vocab.json"
