device: cpu
epochs: 100
iterations: 0
logs: logs
checkpoints: checkpoints
validation_steps: 4
autosave_mins: 10
model:
  class: BasicLstmChatter
  checkpoint: ""
  parameters: 
    max_length: 60
    num_embeddings: 10000
    layers: 2
    do: 0.5
    hidden_size: 256
    embedding_dim: 128
optimizer:
  type: RMSprop
  parameters:
    lr: 0.01
dataset:
  tokenizer:
    path: ""
    max_words: 10000
  val_share: 0.05
  train_batch: 32
  val_batch: 16
  class: ChatDataset
  parameters:
    path: data/dataset.csv
    max_words: 60
    limit: 0
